### ISSUE TITLE
Release checklist for v7.1

### ISSUE THREAD

**Issue by dondi** [dondi/GRNsight#1077]
- [x] In the days leading up to the release, all open issues that need to be resolved before the release will be given the label "for next release".
- [x] Any new or changed client-side features need to be documented on the [Client Side Testing Document](https://github.com/dondi/GRNsight/wiki/Client-Side-Testing-Document) page.
    - [x] the [feature JSON files](https://github.com/dondi/GRNsight-archive/tree/main/documents/developer_documents/testing_script_generator) file should be updated
    - [x] the new feature also needs to be added to the [Pull Request Checklist](https://github.com/dondi/GRNsight/wiki/Pull-Request-Checklist)
- [x] Test the candidate build (typically the `beta` branch)
- [x] Merge the branch(es) under development (typically `beta`) into `master`
    - [x] Resolve any version control conflicts
    - [x] Test the final merged version
    - [x] Perform hotfixes on `master` as needed
- [x] Update README.md at top-level directory of master branch, if necessary
    - [x] Update Travis and Coveralls badges to reference the master branch
- [x] Tag the final, tested version as `v#.#.#` (all three numbers are required, even if `0`; see _npm_ step below)
    - [x] Update version numbers in _package.json_
    - [x] Remember that the tag needs to be pushed to GitHub: `git push origin <tag-name>`
- [x] Create draft release item on Github repository (name it exactly like the tag)
    - [x] Make release notes: a list of new features/bug fixes with issue numbers covered by this release.  Note that this at least will be the ones labeled "for next release", with possible others.
- [x] Publish GitHub release item
- [x] Publish release to GRNsight home page
    - [x] Refresh (pull) the `master` clone on _grnsight.lmucs.org_
    - [x] Update the version number and modification date on `gh-pages`
    - [x] Update the About page with release notes (GitHub release item without issue numbers)
        - [x] Update the browser version compatibility statement with the latest version of Chrome and Firefox for which the new GRNsight version has been tested.
        - [x] Update modification date
    - [x] Add news item about the release to the News page
        - [x] Update modification date
        - [x] Link news item to the corresponding release notes in the About page
    - [x] Update Documentation page with any new features or updates to old features
- [x] Increment beta version
    - [x] Merge released `master` with `beta`, especially if hotfixes/merges were made on `master`
    - [x] Update version number and modified date on `gh-pages`
    - [x] Update Travis and Coveralls badges to reference the beta branch
    - [x] Refresh (pull) the `beta` clone on _grnsight.cs.lmu.edu_
- [x] Publish to _npm_ (`npm publish`)
    - [x] _npm_ requires all `.0`s in the semantic version
- [x] Update version number/other relevant information at current bioinformatics listing sites
    - [x] Elixir 
        - [x] Then change hyperlink on the GRNsight Links page, if necessary
- [x] Get DOI for new release from Zenodo
    - [x] Verify that the badge in README.md at top level of repo is correct
      (it might be necessary to invoke `curl -X PURGE https://camo.githubusercontent.com/`_camo-GitHub-id_ in order to update the badge image)
    - [x] Verify that CITATION.md file DOI links to the new release, updating if necessary
    - [x] Verify that "How to cite GRNsight" section on About page links to the new release, updating if necessary

**Comment by ntran18** [comment]
[v7.1.0]

GRNsight v7.1.0 includes the following new features and bug fixes:
- Features:
   - Lock Force Parameters are available for both Force Graph and Grid Layout. (#1016)
   - Adding Protein-protein interaction (PPI) demo (#1065)
- Bug Fixes:
   - Remove the checks from Force Graph and Grid Layout options from the menu. (#1016)
   - The current state of the Force Graph/ Grid Layout is reflected consistently between the menu and the side panel. (#1016)
   - Selected dataset is centralized to an internal state value, allowing the menu and the side panel to choose and display the same dataset. (#1033)
   - Fixed the button "Restrict Graph to Viewport" from the menu to work correctly (#1034)
   - Fixed the modals not to close when clicking or dragging the modal window with the mouse (#1029)

**Comment by ntran18** [comment]
I've shared the details of my release note's draft above. I also make a draft.

**Comment by dondi** [comment]
Upon reviewing current status, we refreshed our memory to note that:
* We had merged into `master` but didn't update the server host
* Version number will be 7.1.0 for production and beta will shift to 7.1.1
* We will restart the release procedure since it’s been a while

**Comment by ceciliazaragoza** [comment]
Here are my additions for the release notes draft:
- Features:
   - Restrict to Viewport is enabled for D-pad and Zoom (#1083)
- Bug Fixes:
   - Fixed Node Coloring Top Menu Options from disappearing when uncheck "node coloring" box on side panel (#1081)

**Comment by ntran18** [comment]
Updated the wiki for the [feature JSON files](https://github.com/dondi/GRNsight-archive/tree/main/documents/developer_documents/testing_script_generator) -  [Pull Request](https://github.com/dondi/GRNsight-archive/pull/1)

**Comment by dondi** [comment]
Per our 9/4 meeting, the presence of the PPI network data is a key part of our release. #1106 has a link to the Box folder containing existing data and can be used for comparison

For strategic reasons, let’s go about it in this way:
* @ntran18, @ceciliazaragoza, and @akaiap will run the scripts on their respective machines individually in order to test/validate the correctness of the data
* Loading the scripts in this way will also ensure that everyone on the team is familiar with the process, and sets everyone up for a potential future project to automate the data update
* Once loading is successful on local machines, we can have a session with @dondi to perform the load on the server
* When the server database is updated, we can test `beta`
* Because the 2024-03-19 load is incomplete, upon successful loading of 2024-09-xx, we will delete 2024-03-19

Each individual should post a comment here as an update, indicating if any issues were encountered

**Comment by ntran18** [comment]
Unfortunately, @ceciliazaragoza and @akaiap won't be able to run the database scripts because the link is down. https://www.yeastgenome.org/blog/yeastmine-shutting-down-july-15. The database is migrated to [AllianceMine](https://www.alliancegenome.org/bluegenes/alliancemine); however, this website doesn't have a service to download the database. 
### AllianceMine

- Need to do more research about this website, such as how to build a query to get data.
   - Tried to query gene from AllianceMine using this query 
<img width="542" alt="image" src="https://github.com/user-attachments/assets/7e77616a-9c2b-483b-a6db-e5794f00ce01">

- Have an example code to download data, but the service link provided is not working. 
### Investigations
### Genes
All analysis about genes is done in [here](
https://docs.google.com/spreadsheets/d/1bDwptPyced9WCO_ae8NfQpEwUw1l2LMVjo2rd8WJGbw/edit?usp=sharing)

Look at both GRN genes and PPI genes and genes downloaded from AllianceMine.

|               |GRN     | PPI   | Alliance| 
|-------- |------ |------|------|
|# genes | 6514 | 6713 | 7336|
|#genes without display names | 6514 | 5791 | 5569

|               | with Alliance data | without Alliance data|
|---------|------------------|----------------------|
|# distinct genes| 7336            | 7016 |
|# distinct genes w/o empty display name | 6854 | 6683|

The following table shows missing genes between each dataset, comparing GRN, PPI, and Alliance.
|              | GRN | PPI  | Alliance |
|--------|----|----|----------|
|GRN      |0  | 303 | 0|
|PPI| 502 | 0 | 0|
|Alliance | 822 | 623 | 0|

Ex: 303 genes exist in the GRN gene table, but not in PPI. 

More numbers ... 
 - 17 gene_display_id in GRN are different from PPI 
 - 590 gene_display_id in PPI are different from GRN (all of those gene_display_id in PPI are None or empty, whereas GRN has different naming). 
 - Within 520 addition genes in Alliance compare to PPI and GRN, there are only 171 genes that have display name. 

#### Database Code
I found some errors with the code. I created the union gene table, and the union missing/update gene files. This can only be apply if both PPI and GRN gene table are exactly similar to each other. So I need to update the script to make both PPI and GRN table to have the same value first before I can use the current code. 

### Proposed Solutions:
#### Solution 1
 In March, I downloaded data to my machine; they are still there, so we can reuse it.
 **Pros:** 
- Don't need to download data again

**Cons:**
- Don't know if there is a problem with the data
- No fresh data
- Need to update current loader_update code. 

### Solution 2 [Recommended]
Download data directly from AllianceMine
**Pros:**:
- Have data up-to-date
- Have more genes

**Cons:**
- Clean data
- Check if the data aligns with old data

I think we should go with data from AllianceMine, since all Yeastmine data is transferred to AllienceMine, and we can have data with the newest source. But we also can check whether new genes should be added. See this link for [genes tables](https://docs.google.com/spreadsheets/d/1bDwptPyced9WCO_ae8NfQpEwUw1l2LMVjo2rd8WJGbw/edit?usp=sharing)

**Comment by dondi** [comment]
After discussing the YeastMine/AllianceMine transition, we will proceed as follows:
* Original Solution 2 will be our long-term approach regardless
* We will go with this revised version of Solution 1 in order to get this imminent production release of GRNsight out:
    * @ntran18  will share the download files w/ @ceciliazaragoza and @akaiap 
    * The existing script will be modified to skip the portions that contact YeastMine, and the code can go straight to the point where the files are being read (if commits are desired, they can be placed on a branch)
    * We then proceed as previously planned, with the local databases being looked at and tested (to recap: we want to have complete PPI data for March 2024)
    * Once data validation succeeds on local machines, we can plan a session with @dondi where we update the production database then proceed with software release
* We will start an issue for Solution 2 and that will become one of our fall goals for GRNsight post-release

**Comment by ntran18** [comment]
Downloaded files are in [GRN-Release-7.1 Database Backups](https://lmu.box.com/s/fg1mochdaxn1mtlfp4vnns2xbw88ewdu)

## Instructions
### 1. Switch to `maika-1077` branch
```
git fetch origin
git switch maika-1077
```
### 2. Download files from [Box](https://lmu.box.com/s/fg1mochdaxn1mtlfp4vnns2xbw88ewdu)
Please place the downloaded files into the correct folders as shown in Box.
```
___ database
      |____ network-database
               |____ script-results
                         |____ processed_loader_files
                                  |____ gene.csv
      |____ protein-protein-database
               |____ script-results
                        |____ processed-loader-files
                                  |____ gene.csv
                                  |____ network.csv 
                                  |____ ....
 ```
 ### 3. Filtering missing and updated data
After getting all the downloaded files, we need to get missing/ updated genes for both GRN and PPI, and missing/updated proteins for PPI. All the code is writing in `filter_update.py`. The file need the address to database to access to database and collect all the current genes and proteins that the databases have for comparison. After running this script, you will see `missing-genes.csv`, `update-genes.csv` in `processed-loader-files` for both `network-database` and `protein-protein-database`, also `missing-protein.csv` and `update-protein.csv`.

For Macbook, please run:
```
DB_URL="postgresql://[<db_user>:<password>]@<address to database>/<database name>" python3 filter_update.py
```
Ex:
```
DB_URL="postgresql://postgres@localhost/postgres" python3 filter_update.py
```
### 4. Loading data into the database
The script below will update the database for either GRN or PPI, depending on what we provide in the command. 

```
python3 loader_update.py --network=[GRN/ PPI] | psql postgresql://localhost/postgres
```
For this time, please try `--network=PPI` since we want to update the PPI database. 

```
python3 loader_update.py --network= PPI | psql postgresql://localhost/postgres
```

Also, we want to fix #1106 issue, so we need to update gene table in GRN. In `loader_update.py`, comment the code in load_grn_data_into_database() like this:
![image](https://github.com/user-attachments/assets/5d747e06-495f-4335-9adb-a6fc178e00ac)

This will make sure that we only update or adding new genes into the genes table, without touching `source` table or `network` table. 

Now, running this script to update GRN's gene table
```
python3 loader_update.py --network= GRN | psql postgresql://localhost/postgres
```

**Comment by ntran18** [comment]
On Friday, I worked with @ceciliazaragoza and @akaiap to update the database and test the code. Both @ceciliazaragoza and @akaiap can update the GRN gene table and PPI tables.

I will plan a session with @dondi to update production database.

**Comment by dondi** [comment]
@ntran18 @ceciliazaragoza and @dondi had a Zoom session where we ran the database scripts on the AWS instance. We caught some final bugs in the scripts and @ntran18 committed those fixes to `beta`

So the current status is that the _beta_ deployment on GRNsight should now have updated PPI network information for March 2024. The `beta` branch needs to be merged into `master` but there are some conflicts which could not be resolved on the spot

@dondi will look at these and aim to finish the merge + deploy

**Comment by dondi** [comment]
Merge has been done (reconciling the conflicting changes in _database/README.md_ took some doing 😅) and 7.1 has now been deployed. We’ll need a re-review of the database README to ensure that I resolved conflicts correctly, plus live testing of production. We can then proceed with finishing up the release

**Comment by dondi** [comment]
- items relating README.md were checked off but there are potential more extensive changes to do with them (e.g., #1118, etc.)
- Tag for 7.1.0 already exists but that is now obsolete (from January); we will re-tag after a round of testing in production
- The release notes are current but are linked to the aforementioned obsolete tag; to be safe, I am copying the contents here. We can revisit the final version of the GitHub Release after the final 7.1.0 tag has been made
    - Release notes for 7.0.0 (which was never released) should be integrated into 7.1.0: https://github.com/dondi/GRNsight/pull/1039
- Turned out that @dondi already did the publishing of the software and the Home website; however, the About and News pages need to be updated
- Full documentation update may need to be on-going; checked off for now but will need future review
- Beta update items have not yet been done; for now, beta is identical to master. When master is finalized, we can merge into beta and perform those tasks
- Publication items to Elixir and DOI should update automatically upon publishing to `npm`

GRNsight v7.1.0 includes the following new features and bug fixes:
- Features:
   - Lock Force Parameters are available for both Force Graph and Grid Layout. (#1016)
   - Adding Protein-protein interaction (PPI) demo (#1065)
   - Restrict to Viewport is enabled for D-pad and Zoom (#1083)
- Bug Fixes:
   - Remove the checks from Force Graph and Grid Layout options from the menu. (#1016)
   - The current state of the Force Graph/ Grid Layout is reflected consistently between the menu and the side panel. (#1016)
   - Selected dataset is centralized to an internal state value, allowing the menu and the side panel to choose and display the same dataset. (#1033)
   - Fixed the button "Restrict Graph to Viewport" from the menu to work correctly (#1034)
   - Fixed the modals not to close when clicking or dragging the modal window with the mouse (#1029)
   - Fixed Node Coloring Top Menu Options from disappearing when uncheck "node coloring" box on side panel (#1081)

**Comment by ntran18** [comment]
Updated release notes for version 7.1.0

GRNsight v7.1.0 includes the following new features and bug fixes:
- Features:
   - Lock Force Parameters are available for both Force Graph and Grid Layout. (#1016)
   - Protein Protein Physical Interactions Database and UI (https://github.com/dondi/GRNsight/issues/1028, https://github.com/dondi/GRNsight/issues/1020)
   - Adding Protein-protein interaction (PPI) demo (#1065)
   - Restrict to Viewport is enabled for D-pad and Zoom (#1083)
- Enhancements:
   - Change order of Yeastmine versions in generate GRN modal (https://github.com/dondi/GRNsight/issues/1035)
   - Filename and display nomenclature for YeastMine-generated Networks (https://github.com/dondi/GRNsight/issues/983)
- Bug Fixes:
   - Remove the checks from Force Graph and Grid Layout options from the menu. (#1016)
   - The current state of the Force Graph/ Grid Layout is reflected consistently between the menu and the side panel. (#1016)
   - Selected dataset is centralized to an internal state value, allowing the menu and the side panel to choose and display the same dataset. (#1033)
   - Fixed the button "Restrict Graph to Viewport" from the menu to work correctly (#1034)
   - Fixed the modals not to close when clicking or dragging the modal window with the mouse (#1029)
   - Fixed Node Coloring Top Menu Options from disappearing when uncheck "node coloring" box on side panel (#1081)
- Documentation:
   - Database setup in Initial Setup wiki (https://github.com/dondi/GRNsight/issues/1011)
   - Database update instruction (https://github.com/dondi/GRNsight/pull/1113)

**Comment by ntran18** [comment]
- Verified database README.md is correct.
- Verified the database in the production
      - One of the new protein is Ank1p, and it has connection with Bas1p. If you try in 2023 database, there would be no connection between these 2 proteins, but if you try the 2024 database, there will be a connection.

**Comment by ceciliazaragoza** [comment]
- Tested restrict graph to viewport feature on master and created a PR #1119 for a small hotfix to refresh the graph when restrict graph to viewport feature clicked in navbar.

**Comment by akaiap** [comment]
- Conducted client-side testing on the Beta version.
- Reviewed and investigated previous issue #1074 to determine the next steps.

**Comment by dondi** [comment]
I checked on Zenodo and it turned out there was an error when it tried to sync up v7.1.1 last week. The error has been fixed but I have not figured out how to get it to retry the sync

As a workaround for now, I published the v7.1.0 release that had been left in draft form. That has been picked up and what is visible in Zenodo

**Comment by dondi** [comment]
I’m not sure if this is visible without logging in to Zenodo, but this is what its log says:

<img width="562" alt="image" src="https://github.com/user-attachments/assets/baf4976e-b2fe-4bfa-b2b0-de97cc3b8377">

It can be reached via the My Account > GitHub menu item if one is logged in and configured with our GRNsight repository

**Comment by dondi** [comment]
Zenodo issue was resolved with a version number bump _just for Zenodo_; Maika's PR was also merged
