### ISSUE TITLE
Task list for Week of 9/19

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#336]
As noted at the meeting, the testing suite needs to be audited before any further coding tasks.  Accordingly, the tasks for this week are:
- [x] #335 Clean-up test suite (all hands on deck)
- [ ] @mihirsamdarshi will continue work on updating state diagram with @yshin4 #326 
- [ ] @yshin4 will figure out issue with npm install and verify what packages are needed #334 
- [ ] @kdahlquist will review #325 
- [x] don't forget that we are meeting at 3:00 next week in LSB 118 for @NAnguiano's journal club #331 

I anticipate that this will take all week (or longer), but the next task after that will be to complete the merge #332.

**Comment by kdahlquist** [comment]
moving unfinished tasks to issue #338 .
