### ISSUE TITLE
Task list Week of 10/3

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#338]
- [ ] @mihirsamdarshi will continue work on updating state diagram with @yshin4 #326 (almost done)
- [x] @yshin4 will figure out issue with npm install and verify what packages are needed #334 
- [ ] complete the merge #332.
- [ ] #339, handling of extraneous data in the test suite using strictness parameter
- [x] #337 bad gateway bug

**Comment by kdahlquist** [comment]
All open tasks have been shifted over to #342.
