### ISSUE TITLE
Task list for week of 10/10

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#342]
- [x] #326 @mihirsamdarshi  needs to complete the state diagram ASAP so he can move on to the next priority.
- [x] #334 @anuvarsh will finish up adding the last two packages to the package.json 
- [ ] #339, @anuvarsh handling of extraneous data in the test suite using strictness parameter; need to add text to error message
- [ ] #285, once the other two tasks are completed, @anuvarsh will move onto working on hiding or showing all the weights 
- [ ] #300 @yshin4 and @mihirsamdarshi will move on to working on refactoring the test suite; see notes on the issue.
- [ ] #159 @NAnguiano will move on to working making options for a small, medium, and large bounding box for the graph display

Remember that @dondi will be traveling Wednesday through Friday this week, but will be able to respond to messages.

**Comment by kdahlquist** [comment]
Outstanding tasks have been moved over to #346.
