### ISSUE TITLE
Task list for week of 10/17

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#346]
- [x] #339, @anuvarsh handling of extraneous data in the test suite last little niggling details
- [ ] #285, once the other two tasks are completed, @anuvarsh will move onto working on hiding or showing all the weights 
- [ ] #300 @yshin4 and @mihirsamdarshi will move on to working on refactoring the test suite. @yshin4 will post her notes on syntactic vs. semantic on the wiki and she and @mihirsamdarshi will divvy up the semantic ones to refactor.
- [ ] #345 @NAnguiano will work on setting the toggle switches so we can have the design discussion about size/zoom/scroll/hard v. infinite boundary
- [ ] #326: @kdahlquist has a review requested on this.

**Comment by kdahlquist** [comment]
Relevant tasks have been moved over to #348.
