### ISSUE TITLE
Task List for Week of 10/24

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#348]
- [ ] #285, @anuvarsh will work on hiding or showing all the weights 
- [ ] #300 @yshin4 and @mihirsamdarshi will work on refactoring the test suite. @yshin4 will work on creating the semantic test for excluding all special characters except for _ and -; @mihirsamdarshi will work on creating the semanticChecker function, moving the code testing for gene name length to the checker, calling it from SIF and GraphML.
- [x] #345 @NAnguiano will work on fixing the bug with reload #347, and then doing the rest of the toggle switches so we can have the design discussion about size/zoom/scroll/hard v. infinite boundary
- [ ] #326: @kdahlquist still has a review requested on this.

**Comment by kdahlquist** [comment]
The GRNmap Data Analysis team is meeting next Monday (10/31) in LSB 118 (first floor conference room) at 3:00.  I thought we could do our meeting in there as well since it is immediately afterwards.  Also, if @NAnguiano has something to show us with regards to the bounding box, it would be good to see it on the big screen.

**Comment by dondi** [comment]
@mihirsamdarshi has defined the function but will get it to a working state before committing; @yshin4 has finished the modification for erroring out on special characters.

**Comment by dondi** [comment]
Up next, @yshin4 will integrate her special characters check into @mihirsamdarshi's checker function. The tests should all still pass, plus SIF and GraphML files that have special characters in their nodes should now also be flagged for errors.

After this, @mihirsamdarshi will integrate gene name length checks into the function, and @yshin4 can work on network size.

**Comment by dondi** [comment]
@NAnguiano will wrap up #347 by mimicking the reload behavior on master. This will eliminate the current redundancy in the beta fix.

**Comment by dondi** [comment]
For #345, @NAnguiano indicated how the scroll wheel is overloaded for both scrolling and zooming. For various reasons we will use the scroll wheel exclusively for scrolling/panning and @NAnguiano will come up with a distinct control for zooming (e.g., slider, +/- button, magnifying glass, etc.).

For ease of feedback @NAnguiano may want to coordinate with @anuvarsh so that the deployed beta can be updated in order for the group to try this out as needed.

**Comment by kdahlquist** [comment]
all open tasks moved to new issue #349.
