### ISSUE TITLE
Task list for week of 11/14 through 12/5

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#349]
- [ ] #285, @anuvarsh will work on hiding or showing all the weights 
- [ ] #300 Up next, @yshin4 will integrate her special characters check into @mihirsamdarshi's checker function. The tests should all still pass, plus SIF and GraphML files that have special characters in their nodes should now also be flagged for errors.  After this, @mihirsamdarshi will integrate gene name length checks into the function, and @yshin4 can work on network size. 
- [ ] #345 toggle switches so we can have the design discussion about size and scrolling are working; zoom and hard v. infinite boundary are not done yet.  @NAnguiano indicated how the scroll wheel is overloaded for both scrolling and zooming. For various reasons we will use the scroll wheel exclusively for scrolling/panning and @NAnguiano will come up with a distinct control for zooming (e.g., slider, +/- button, magnifying glass, etc.). For ease of feedback @NAnguiano may want to coordinate with @anuvarsh so that the deployed beta can be updated in order for the group to try this out as needed.
- [ ] #326: @kdahlquist still has a review requested on this.

**Comment by kdahlquist** [comment]
The GRNsight meetings will take place in LSB 118 for the rest of the semester.

We will be doing code review and demos on the big screen.

@mihirsamdarshi, please be sure to push your work either to the main GRNsight repo or to a fork so that we can see your work in progress at the meeting.

Don't forget to post a comment to your issues--see you Monday!

**Comment by mihirsamdarshi** [comment]
@yshin4 refactored her special character checker. @mihirsamdarshi I created a new file, ran it and broke everything, so I decided to make a new branch called testFixes. I started to redo the new checker function file, and @yshin4 helped me move everything to this new semanticchecker.js file. We are now confused as to how to link spreadsheetcontroller.js to our new semanticchecker.js file.

**Comment by kdahlquist** [comment]
Just a reminder that @kdahlquist will not to be able to make the meeting today.  Keep me posted with updates to the respective issues.

**Comment by dondi** [comment]
Yes, and due to my child pickup schedule, my arrival may be unpredictable. Students can use the time prior to my arrival as finalizing/wrap-up time so that we can jump right into issue review once I get there.

**Comment by yshin4** [comment]
@yshin4 and @mihirsamdarshi are still working on refactoring semanticChecker and @yshin4 talked to dondi about how to implement semanticchecker function by using require and module.export. We will be working on testFixes branch until we safely move semantic errors and pass all the tests that are currently failing due to refactoring progress.

**Comment by dondi** [comment]
@NAnguiano had some trouble working with the boundary/boundless node positioning algorithm. @dondi pointed the `tick` function where we have the final mapping of nodes to their positions. However, that function is affected by the force graph algorithm which injects an initial _(x, y)_ coordinate into the nodes. @NAnguiano will look at this behavior without any of the additional code that is in there, then proceed based on what she sees.

**Comment by kdahlquist** [comment]
For #300, the key here is to forget about the input source and focus solely on the network data structure that each file-reading routine returns. So `semanticChecker` needs to be refactored to just iterate over the portions of `network` and nothing else.

**Comment by kdahlquist** [comment]
To enforce this, reduce the arguments to `semanticChecker` so that it only accepts `network`. All of the other existing parameters are specific to the spreadsheet import routine and will not exist with the importers for SIF, GraphML, and potential future files.

**Comment by kdahlquist** [comment]
@dondi thinks @anuvarsh is pretty close, but just needs a deeper understanding of graph.js. She may come during a separate session to review this.

**Comment by kdahlquist** [comment]
@mihirsamdarshi had a question about the supplementary parameters other than `network`; @dondi responded by saying that these were all just convenience values and are easily derivable from the original `network` object.

**Comment by kdahlquist** [comment]
@NAnguiano had the XMLPipeDB presentation + transportation timing issues so will return to the infinite/finite zooming/sizing issue for next week.

**Comment by kdahlquist** [comment]
For @anuvarsh, another way to think about the implementation is in terms of the divergent behavior: when the weights are only visible upon mouseover, their position is determined by the mouse position. When the weights are always visible, their position is determined by the centroid of their attached edges. When the weights are _in_visible, we actually don't care what happens to them, so by reduction we can say that we only need to change weight locations if we are not on mouseover mode.

**Comment by yshin4** [comment]
For checkDuplicates function to check if there are any duplicate gene names, I tried to use network.lists[i].source.name and target.name but apparently they are both undefined. If I do console.log(network.lists[i].source) it gives me numbers. May I visit during office hours today to solve this issue? @dondi

**Comment by dondi** [comment]
Sure you can come in, but real quick, those numbers are indices into the genes array. So a source of 4 means the source is `network.genes[4]`.

**Comment by kdahlquist** [comment]
open tasks moved to #359
