### ISSUE TITLE
Task list for Weeks of 1/12 and 1/18

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#359]
Tasks for @ebachoura and @eileenchoe: 
- [x] @ebachoura and @eileenchoe need to do a code walkthrough
- [x] @ebachoura and @eileenchoe need to add themselves to the People page of the website.
- [ ] #326 @ebachoura and @eileenchoe update state diagram with feature to show/hide all weights
- [ ] #361 do npm install on their computers based on documentation on the wiki; work on automating the npm install so we can just do "npm install grnsight"
- [ ] work on "syntactic" tests for SIF and graphml input files. #362 and #363

Tasks for @yshin4 and @mihirsamdarshi:
- [ ] continue work on #300 

Tasks for @NAnguiano 
- [ ] create issues for all the tasks required for CMSI 402
- [ ] work on finite/infinite bounding box #345 

Tasks for @anuvarsh and @mihirsamdarshi:
- [x] Southern California Conference for Systems Biology abstract #360
- [ ] Southern California Conference for Systems Biology poster

Tasks for @anuvarsh:
- [x] begin work on allowing user to adjust normalization factor for edge thickness #264 
- [x] can create issues for due dates for BIOL 598
- [x] Title and Annotated Bibliography #367 

Task for @kdahlquist
- [x] #285 review requested

Everybody:
- [x] #356 read article about github

**Comment by kdahlquist** [comment]
I have added details to the task lists.  Please check out the previous comment on this issue.

**Comment by kdahlquist** [comment]
@ebachoura and @eileenchoe, don't forget to change the last modified date when update website.  I saw you made the change, but did not change the date.

**Comment by eileenchoe** [comment]
@NAnguiano did a code walkthrough with @ebachoura and me this afternoon. Thanks for the catch @kdahlquist, last modified date is now updated on the People page.

**Comment by dondi** [comment]
@NAnguiano has been focused on her 402 tasks and will return to infinite scroll after.

**Comment by kdahlquist** [comment]
Open issues have been moved to #376.
