### ISSUE TITLE
Summer 2017 Research Task List

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#380]
Juniors and sophomores, let @kdahlquist know if you are interested in working on GRNsight this summer by the end of next week (Feb. 3) so that we can apply for funding.

**Comment by ebachoura** [comment]
I am interested in doing the 3 week summer research session!

**Comment by kdahlquist** [comment]
Great--so we will have a 3-week sprint on GRNsight with @ebachoura , @eileenchoe , and @mihirsamdarshi .  Looking forward to it!  Going to close this one now because no further action is required for now.

**Comment by kdahlquist** [comment]
Re-opening this issue because summer is getting closer.  

The three week period we will be working is the first three weeks of Summer Session I:  Monday, May 15 to Friday, June 2 (we are off Memorial Day for the holiday).

We will be working from 9:00 to approximately 6:00 PM each day (it depends on how long you take for lunch; we will be working 8-hour days).

We will begin each day with a stand-up at 9:00 AM to discuss the day's work.  @kdahlquist will be teaching a summer course from 10-12 Monday through Thursday, but will otherwise be available.  We will have a lunch lab meeting once a week for longer presentations and discussions where lunch will be provided.

You will be paid on an hourly basis through MyTime.  Instructions on how to get employed in the position will be coming later in the month.

**Comment by kdahlquist** [comment]
Barbeque for today 12-2 has been moved to the Bird's nest.

**Comment by kdahlquist** [comment]
We'll do a Hangout witih @dondi in @kdahlquist's lab later today at 4:00.  @kdahlquist and @dondi will start out by themselves and then invite in @mihirsamdarshi and @eileenchoe at about 4:15 or so.

**Comment by kdahlquist** [comment]
As noted in the meeting today, we only have about 8 days left of research.  To focus us, I'm starting a task list like we did during the semester.

For @eileenchoe 
- [ ] #497: merge branches beta and normalization
- [ ] #496: SWE abstract
- [ ] #426: SIGGRAPH poster
- [ ] #326: automatics client-side test generator
- [ ] #468, #471, #484, #485: zoom issues

For @mihirsamdarshi 
- [ ] #497: merge branches beta and normalization
- [ ] 264: normalization of edge weights and grey threshold 

For @kdahlquist
- [ ] review requesteds

For @dondi 
- [ ] review requesteds

**Comment by kdahlquist** [comment]
We'll have our Google Hangout with @dondi today at 2:00.  I'll send the link as usual via e-mail.

**Comment by eileenchoe** [comment]
Ok, we've been working on the merge all morning. About halfway done, will try to get at least the functionality finished by the meeting since we've been ignoring formatting discrepancies so far.

**Comment by kdahlquist** [comment]
As long as you are at a good stopping place by 2:00, we should be fine.

**Comment by kdahlquist** [comment]
@dondi, let us know by commenting here what time is good for a hangout on Friday.  For me, sometime after 11:00 would be ideal.

**Comment by dondi** [comment]
It will be after 11am for sure; I estimate close to 2pm just like Wednesday. I’ll have a better feel on the day itself but that is what I expect.

**Comment by dondi** [comment]
Confirming that 2pm looks good.

**Comment by kdahlquist** [comment]
OK, I'll send out the hangout in about an hour.

**Comment by kdahlquist** [comment]
Our next face-to-face meeting will be at noon on Tuesday, May 30 in LSB 331 (the classroom on the third floor) because the other conference rooms were booked.  Pizza will be provided.

**Comment by kdahlquist** [comment]
Thanks to @mihirsamdarshi and @eileenchoe for all the great work during the summer sprint--enjoy the rest of your summer!
