### ISSUE TITLE
Task List for Weeks of 2/9 and 2/15

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#391]
For @anuvarsh 
- [x] #285, finalize refresh issue with showing/hiding weights (priority 0)
- [ ] #264, user defined normalization factor (after above completed, or if need a break from it)

For @yshin4 (generally in the vein of tidying up the graph layout features/bugs)
- [x] #343, verify and then close this one
- [ ] #333, reduce white space on either side of label (priority 0)
- [ ] #318, long node labels mess up self-regulatory arrows (priority 0.5) because these two seem related

For @mihirsamdarshi 
- [x] #382, needs to sign off on this so we can close issue
- [ ] #386, semantic checker needs to be integrated into SIF and GraphML importers (priority 0)
- [ ] #355, but where network loads with black edges and cyan blunt end markers due to real number weight values in sheet called "network" instead of "network_optimized_weights" (priority 0.5)

For @eileenchoe 
- [ ] #362, syntactic tests for SIF (priority 0)
- [ ] #326, write program to generate state diagram (with @ebachoura , priority 0.5)
- [ ] #361, finalize pending decisions by @kdahlquist and @dondi (priority 0.5)

For @ebachoura 
- [x] #382, needs to sign off on this so we can close issue
- [ ] #363, syntactic tests for GraphML (priority 0)
- [ ] #326, write program to generate state diagram (with @eileenchoe  , priority 0.5)
- [ ] #361, finalize pending decisions by @kdahlquist and @dondi (priority 0.5) 

For @NAnguiano 
- [x] #345, design decisions about this will be made on 2/13, after which new issues will be opened for implementation and this one can be closed (priority 0)
- [ ] #395 Implement automatic discovery of initial drafting board and viewport size (priority 0)
- [ ] #397 Implement preference to change viewport size between small, medium, large (priority 0)
- [ ] #290, work on hierarchical layout (priority 0.5)

For @kdahlquist
- [ ] #360, upload poster to slideshare, update publication and news web pages
- [x] #387, review requested

For @dondi 
- [ ] #361, @kdahlquist wasn't able to remember what the final decision was on this one, @dondi needs to give direction

**Comment by kdahlquist** [comment]
remaining open issues moved to #403.
