### ISSUE TITLE
Task List for Weeks of 2/23 and 3/2

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#403]
For @anuvarsh 
- [ ] #264, user defined normalization factor (priority 0)
- [ ] #370, Materials and Methods/ Results (priority 0)

For @yshin4 (generally in the vein of tidying up the graph layout features/bugs)
- [ ] #333, reduce white space on either side of label (priority 0)
- [ ] #318, long node labels mess up self-regulatory arrows (priority 0.5) because these two seem related
- [ ] #392, make arrowheads bigger for thinnest black, grey, magenta, and cyan arrows (0.5) because if working on edge markers, might as well as tackle related issues
- [ ] #188, another edge marker-related issue (priority 0.5)

For @mihirsamdarshi 
- [x] #386; @eileenchoe and @ebachoura may have already finished this one
- [ ] #355, bug where network loads with black edges and cyan blunt end markers due to real number weight values in sheet called "network" instead of "network_optimized_weights" (priority 0)
- [ ] #381, update color scheme to be color blind-friendly (priority 0.5)

For @eileenchoe 
- [x] #386; @eileenchoe and @ebachoura may have already finished this one
- [ ] #362, syntactic tests for SIF (priority 0); set up meeting with @kdahlquist
- [ ] #326, write program to generate state diagram (with @ebachoura , priority 0.5)
- [ ] #361, finalize pending decisions by @kdahlquist and @dondi (priority 0.5)

For @ebachoura 
- [x] #386; @eileenchoe and @ebachoura may have already finished this one
- [ ] #363, syntactic tests for GraphML (priority 0); set up meeting with @kdahlquist
- [ ] #326, write program to generate state diagram (with @eileenchoe  , priority 0.5)
- [ ] #361, finalize pending decisions by @kdahlquist and @dondi (priority 0.5) 

For @NAnguiano 
- [x] #395 Implement automatic discovery of initial drafting board and viewport size (priority 0)
- [x] #397 Implement preference to change viewport size between small, medium, large (priority 0)
- [x] #396 Implement preference for hard and adaptive drafting board size (priority 0)
- [x] #398 Implement adaptive drafting board size (priority 0)
- [x] #399 Implement viewport scrolling and drafting board scaling (priority 0)
- [ ] #290, work on hierarchical layout (priority 0.5)

For @kdahlquist
- [x] #285 review requested, when the change is up on beta
- [ ] #418, upload poster to slideshare, update publication and news web pages

For @dondi 
- [x] #361, @kdahlquist wasn't able to remember what the final decision was on this one, @dondi needs to give direction
- [x] #393, need answer to this question
- [x] #404, please comment

**Comment by kdahlquist** [comment]
Everyone, sign off on #404.

**Comment by kdahlquist** [comment]
Reminder to everyone that now the LMU Symposium prep is over, please return to your assigned issues/tasks for this week.  We will refresh this task list at our meeting on Thursday.

**Comment by kdahlquist** [comment]
All relevant open issues have been moved to #430.
