### ISSUE TITLE
Task list from now to end of the Spring 2017 semester

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#430]
For @anuvarsh 
- [ ] #264, user defined normalization factor (priority 0)
- [x] #422, add release notes to this issue for your features/bug fixes
- [x] #425, preferences

For @yshin4 (generally in the vein of tidying up the graph layout features/bugs)
- [x] #333, reduce white space on either side of label (CLOSED)
- [ ] #318, long node labels mess up self-regulatory arrows (priority 0) because these two seem related
- [ ] #392, make arrowheads bigger for thinnest black, grey, magenta, and cyan arrows (priority 0) size change is done, but need to adjust so tip of point doesn't go behind node box
- [ ] #188, another edge marker-related issue (priority 0.5)
- [ ] #422, add release notes to this issue for your features/bug fixes
- [x] #425, preferences

For @mihirsamdarshi 
- [ ] #355, bug where network loads with black edges and cyan blunt end markers due to real number weight values in sheet called "network" instead of "network_optimized_weights" (priority 0)
- [ ] #381, update color scheme to be color blind-friendly (priority 0.5)
- [ ] #422, add release notes to this issue for your features/bug fixes

For @eileenchoe 
- [x] #364 slider display value bug (priority 0)
- [ ] #417 missing value error (priority 0.5)
- [ ] #428, semantic test for blank file (priority 0.5)
- [ ] #362, syntactic tests for SIF (reset to priority 0.5)
- [ ] #422, add release notes to this issue for your features/bug fixes

For @ebachoura 
- [x] #364 slider display value bug (priority 0)
- [ ] #417 missing value error (priority 0.5)
- [ ] #363, syntactic tests for GraphML (reset to priority 0.5); set up meeting with @anuvarsh to discuss test files
- [ ] #422, add release notes to this issue for your features/bug fixes
- [ ] #425, preferences

For @NAnguiano 
- [x] #396 : Fixed/adaptive bounding box tweaks
- [ ] #399 : Scrolling/Zooming Tweaks
- [x] #411 : UI tweaks
- [x] #443: Bug with weights appearing in the upper left hand corner when "always show weights" is selected
- [ ] #290, work on hierarchical layout (priority 0.5)
- [ ] #422, add release notes to this issue for your features/bug fixes

For @kdahlquist
- [ ] #395 review requested, automatic detection of browser window size
- [ ] #396, #399, #411, review as changes become available on beta
- [ ] #418, upload poster to slideshare, update publication and news web pages
- [ ] #422, add release notes to this issue for your features/bug fixes; write documentation

For @dondi 
- [ ] #396, #399, #411, review as changes become available on beta
- [ ] #386 review requested, integration of semantic checker
- [ ] #429, question about browser backwards compatibility

**Comment by dondi** [comment]
@anuvarsh has made some progress and will have time until next Wednesday, after which she needs to focus on MCAT. The goal we have established is for her to have the functionality working with refresh. We will look into making normalization adjustments without refresh after that, for the remainder of the semester.

**Comment by dondi** [comment]
@mihirsamdarshi was momentarily stuck but @dondi advised him to keep his developer console open so he can see any errors that were emerging, which was what was happening in this case. Upon seeing the error, this immediate issue was fixed during the meeting and he can now proceed.

He is projected to be finished with #355 well before the next technical meeting, so @dondi asked him to proceed to #381 once #355 has been finished, pull-requested, reviewed, and merged.

**Comment by dondi** [comment]
@eileenchoe is on the verge of issuing a pull request for #362, which @dondi will review. She also has a general approach (similar to @ebachoura's) for handling empty files (#428).

**Comment by dondi** [comment]
For @ebachoura, @dondi walked through the process involved in implementing #363, ranging from the tests to how to handle the `err` argument passed by the third-party `parseString` function. @eileenchoe's existing unit tests for her SIF syntactic checker can serve as a pattern for his own unit tests.

**Comment by dondi** [comment]
@dondi relayed to @eileenchoe and @ebachoura that we will be entering a swarm phase to help @NAnguiano with QA-ing her 402 work. At certain milestones, @NAnguiano can ask @eileenchoe and @ebachoura to do a thorough test with all of the combinations for the zooming/bounding box/adaptive settings that she is implementing. @eileenchoe and @ebachoura can report issues and potentially offer fixes to help polish the work.

**Comment by kdahlquist** [comment]
Updated task list for @ebachoura and @eileenchoe to assign #364 as per @NAnguiano's request.  Downgraded their other tasks in the meantime.

**Comment by NAnguiano** [comment]
Updated task list to add #417 to @ebachoura and @eileenchoe.

**Comment by kdahlquist** [comment]
@NAnguiano and @yshin4, any progress to report after today's work session?

**Comment by dondi** [comment]
#417 has been tabled to priority 0.5 so that @eileenchoe and @ebachoura can focus on debugging the combinatorics of @NAnguiano's full feature set.

**Comment by dondi** [comment]
@NAnguiano expects a new pull request for her features tonight.

**Comment by kdahlquist** [comment]
I closed #396, #399, and #411, opening a slew of more granular issues instead.  They have been all marked with a priority level and whether they are for the upcoming release.  I'm not going to try and update this issue right now.  So, @NAnguiano, just please apply the relevant label filter to see what needs to be fixed immediately.

**Comment by kdahlquist** [comment]
I'm closing this.  All open tasks that need to be completed for the next release are labeled as such.  Further notes will go on issue #422: checklist for release.
