### ISSUE TITLE
Spring 2018 Task List

### ISSUE THREAD

**Issue by kdahlquist** [dondi/GRNsight#560]
This issue will have the Task List that will be updated throughout the Spring 2018 semester.

The top priority for everyone for this week is to do the v2.3.0 release.
- [x] #557 the release
- [x] #552 approving the PR
- [x] #555 approving the PR
- [x] #523 port to D3v4 review requested

Then, @yshin4 should:
- [x] #558: block layout
- [ ] #290: hierarchical layout

Then, @eileenchoe should:
- [x] #241: data structure design
- [x] #566 : node coloring

Then, @mihirsamdarshi 
- [ ] #438: allow numbers as node labels
- [x] #568: make gray edges have dashed line instead of solid line
- [x] #564: resolve "qs" package security vulnerability
- [x] #518: change gray threshold value to percent scale

**Comment by yshin4** [comment]
@eileenchoe and @yshin4 met Wednesday and made changes to the file according to @dondi's review. PR merged and updated beta to v2.2.9. This takes care of #552, #555, and #523.

**Comment by yshin4** [comment]
#561 has popped up while testing beta for the release.

**Comment by yshin4** [comment]
Creted v.2.3.0 release draft, @kdahlquist will you please review? Thank you.

**Comment by dondi** [comment]
@mihirsamdarshi is pretty much done with #438 and will issue a pull request soon.

**Comment by dondi** [comment]
Next up for @mihirsamdarshi is #437 and #568.

**Comment by dondi** [comment]
For @yshin4, the trick is to manually trigger what currently happens when a node is dragged: i.e., the node stops being affected by the graph layout simulation. Setting coordinates directly is not enough because it looks like the graph layout just overrides it. So, she needs to find out how to keep the graph layout algorithm from adjusting a manually-set node.

Alternatively, @yshin4 can consider doing a `grid` implementation as an actual layout strategy. This takes more reading of D3 but might also be useful.

**Comment by dondi** [comment]
As a possible workaround, @yshin4 can try loading a small graph, manually drag all of the nodes so that they aren't under the force simulation, and _then_ click the Grid Layout button. This would be a temporary workaround just to see if the grid takes hold, and the task of finding out how to programmatically make the nodes "fixed" can be a separate focus.

**Comment by eileenchoe** [comment]
I will not be attending the meeting this Monday 2/26, since I will be at a grad school visit at UIUC. My update is that I have an outstanding PR #567 for the data structure redesign. @dondi can you please review when you get the chance? @yshin4 has already completed the PR checklist for it. Made progress on node coloring #566 this week, and will continue working on it this week, focusing on removing all hard coded values for the mockup to make it dynamic, and to lay the groundwork for the node coloring UI menu. On Wednesday @yshin4 and I can start talking about the UI redesign necessary for our features.

**Comment by dondi** [comment]
@eileenchoe PR review has been submitted. Good luck at UIUC!

**Comment by kdahlquist** [comment]
At today's meeting let's make the final task list leading up to the v3.0.0 release.  Let's also tag issues to be included in the release with the `for next release` tag and `priority 0`.

Just a note: if you are tagging something as `review requested`, please leave the priority tag in place.  @dondi and @kdahlquist use the priority tag for filtering and might miss something if it is not there.  

I have a sense that this might be a long meeting today with lots of ground to cover.  I'm going to try to come over early, around 11:00, so if anyone can join me we can get started.

**Comment by yshin4** [comment]
I will try to come at 11:00 as well.

**Comment by kdahlquist** [comment]
I'm busy for the next couple of hours, but will do my best to look at beta before I leave at 5:00 today.

**Comment by kdahlquist** [comment]
Congratulations to the team!
